apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker-flask-app-service   # First microservice
            port:
              number: 5000

      - path: /prajwal
        pathType: Prefix
        backend:
          service:
            name: docker-flask2-service      # Second microservice
            port:
              number: 5001

