apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservice1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: microservice1.local   # or your domain / IP
      http:
        paths:
          - path: /prajwal
            pathType: Prefix
            backend:
              service:
                name: microservice1-svc
                port:
                  number: 80
