apiVersion: v1
kind: Service
metadata:
  name: microservice1-svc
spec:
  selector:
    app: microservice1
  ports:
    - protocol: TCP
      port: 80       # Service port (browser will use)
      targetPort: 5000 # Container port where Flask runs
  type: ClusterIP
